import "./globals.css";
export const metadata = {
  title: "Sucoding",
  description: "Generated by Handsome",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
