import Link from "next/link";
import "./globals.css";
export const metadata = {
  title: {
    default: "Next.JS | Sucoding",
    template: "%s | Sucoding",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/blog">Blog</Link>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
