export const metadata = {
  title: {
    absolute: "blog",
  },
  description: "Generated by Next.js",
};

export default function Blog() {
  return (
    <>
      <h1>Blog Component</h1>
    </>
  );
}
